LD_FILE = boards/samd51x19-bootloader.ld
USB_VID = 0x239A
USB_PID = 0x8021
USB_PRODUCT = "sprite_v2a"
USB_MANUFACTURER = "maholli@stanford.edu"

QSPI_FLASH_FILESYSTEM = 0
INTERNAL_FLASH_FILESYSTEM = 1
LONGINT_IMPL = MPZ

CHIP_VARIANT = SAMD51G19A
CHIP_FAMILY = samd51